version: '3'
services:
    kg-cefriel-neo4j: 
      image: neo4j:4.4
      ports:
      # HOST_PORT:CONTAINER_PORT
        - "127.0.0.1:7474:7474"
        - "127.0.0.1:7687:7687"
      restart: on-failure
      volumes: 
        - ${NEO4J_FOLDER:-./}neo4j/data:/data
        - ${NEO4J_FOLDER:-./}neo4j/logs:/logs
        - ${NEO4J_FOLDER:-./}import:/var/lib/neo4j/import
        - ${NEO4J_FOLDER:-./}neo4j/plugins:/plugins 
      environment:
        NEO4J_AUTH: "neo4j/kgCefriel"
        NEO4JLABS_PLUGINS: '["graph-data-science"]'