version: '3'
services:
    corso-kg-postgres:
      image: postgres
      container_name: corso-kg-postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: kgCefriel
        POSTGRES_DB: corso-kg-postgres
      ports:
        - 5432:5432
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - ./data:/data
    corso-kg-neo4j: 
      image: neo4j:4.4
      container_name: corso-kg-neo4j
      ports:
      # HOST_PORT:CONTAINER_PORT
        - "127.0.0.1:7474:7474"
        - "127.0.0.1:7687:7687"
      restart: on-failure
      volumes: 
        - ${NEO4J_FOLDER:-./}neo4j/data:/data
        - ${NEO4J_FOLDER:-./}neo4j/logs:/logs
        - ${NEO4J_FOLDER:-./}data:/var/lib/neo4j/import
        - ${NEO4J_FOLDER:-./}neo4j/plugins:/plugins 
      environment:
        NEO4J_AUTH: "neo4j/kgCefriel"
        NEO4JLABS_PLUGINS: '["apoc","graph-data-science"]'
    load-neo4j:
      image: cefriel/corso-kg:load-neo4j
      container_name: load-neo4j
      build:
        context: .
      volumes:
        - ./data:/code/data
      depends_on:
        - corso-kg-neo4j